### ISSUE TITLE
[BUG] CAPI Explorer - Unable to create resources using yaml file with multi documents

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#15]
**Setup**
- Rancher version: v2.7.9
- Rancher UI Extensions: CAPI UI Extension v0.1.0
- Browser type & version: Chrome Latest

**Describe the bug**
While creating CAPI resources, using yaml file with multi documents separated by --- results in error:
_YAMLException: expected a single document in the stream, but found more_

**To Reproduce**
- Install CAPI UI extension
- Navigate to CAPI explorer under Cluster management
- Under CAPI Clusters, Create from YAML
- Paste the YAML contents or use Read from file to upload yaml file with multi documents separated by ---

**Expected Result**
User must be able to create resources using yaml file with multi documents

**Screenshots**
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/dc3847e9-f18a-485b-928f-ddf58a8ddce7)

**Comment by mantis-toboggan-md** [comment]
>Expected Result
>User must be able to create resources using yaml file with multi documents

This is not the expected behaviour of the 'Create from YAML' button: the CAPI UI extension is in line with the Rancher Dashboard on this one. Users can upload yaml file with multi documents by using the 'import yaml' action within cluster explorer
