### ISSUE TITLE
[BUG] Rancher v2.7 - CAPI Auto-Import heading not visible

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#17]
**Setup**
Rancher version: v2.7.9
Rancher UI Extensions: CAPI UI Extension v0.1.0
Browser type & version: Chrome Latest

**To Reproduce**
- Install CAPI UI extension
- Navigate to local cluster and default namespace
- Check CAPI Auto-import heading

**Expected Result**
CAPI Auto-import heading must be visible

**Screenshots**
Rancher 2.7:
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/52c137f4-0c6e-44f9-842d-a72e66125419)

Rancher 2.8:
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/158c9470-1ac4-47ce-9ec6-ec559200725a)

**Comment by valaparthvi** [comment]
It does not look like this has been fixed on Rancher v2.7-head. I tested with:
Rancher - v2.7-head
Rancher turtles ui - v0.3.0
Rancher turtles - v0.5.0

![image](https://github.com/rancher/capi-ui-extension/assets/11015077/4e4a3a98-c89f-43ca-afbb-fdf80f10fbee)
![Screenshot from 2024-03-22 14-22-16](https://github.com/rancher/capi-ui-extension/assets/11015077/77029aaa-749f-4402-83de-e06b2766a33b)


The same thing works as expected on Rancher 2.8-head

**Comment by valaparthvi** [comment]
We do not support CAPI on 2.7, @cpinjani can you close the issue? I don't see an option to close it.
