### ISSUE TITLE
[BUG] Rancher v2.7 - Extension heading incorrect after installation

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#34]
**Setup**
Rancher version: v2.7-head
Rancher UI Extensions: CAPI UI Extension v0.2.0
Browser type & version: Chrome Latest

**To Reproduce**
- Install CAPI UI extension
- Under Extensions, check extension heading

**Expected Result**
CAPI UI Extension heading must be consistent between Rancher releases

**Screenshots**
2.7:
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/470e33bb-4819-451e-9a6a-947b4d5edcf7)

2.8:
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/adeb2be3-fe57-433e-82b4-c76aca33a087)

**Comment by mantis-toboggan-md** [comment]
This is a bug in rancher/dashboard fixed in 2.8.0 with this PR: https://github.com/rancher/dashboard/pull/9544
