### ISSUE TITLE
Enable CAPI auto-import not available for namespace

### ISSUE THREAD

**Issue by richardcase** [rancher/capi-ui-extension#35]
The **Enable CAPI Auto Import** feature is not available as an action on the namespace. Its only available as an action on the project:

https://github.com/rancher/capi-ui-extension/assets/198425/0ccf4788-8bdf-484c-9e62-0584ec92f738

Rancher Version: v2.8.0
UI Extension Version: v0.2.0

**Comment by cpinjani** [comment]
Validated as fixed on build:
```
v2.8-5348f98d13011641aaac739f77f9b256f8109612-head
v2.7-bd0bb772b60a447d352789b3d7c4368ffe50eecf-head
UI Extension Version: v0.3.0
```
Enable CAPI Auto Import is now only available for namespaces, not for Projects.
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/008915e5-9c70-4097-a0dc-0df7c8ee2e94)

**Comment by richardcase** [comment]
Closing on behalf of @cpinjani
