### ISSUE TITLE
[BUG] Change Sub-Menu name to CAPIProviders

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#44]
**Setup**
Rancher version: v2.8-head
Rancher Turtles: v0.6.0
Rancher UI Extensions: CAPI UI Extension v0.4.0
Browser type & version: Chrome Latest

**To Reproduce**
- Install CAPI UI extension
- Open Cluster Management > CAPI Menu
- Check Infrastructure Providers

**Expected Result**
With new enhancement https://github.com/rancher/capi-ui-extension/issues/13, it seems all providers are now being listed which are of type capiproviders, so we can change Menu name to denote providers appropriately
```
$ kubectl get capiproviders -A
NAMESPACE                           NAME                    TYPE             PROVIDERNAME   INSTALLEDVERSION   PHASE
capd-system                         docker                  infrastructure   docker         v1.4.6             Ready
capi-kubeadm-bootstrap-system       kubeadm-bootstrap       bootstrap        kubeadm        v1.4.6             Ready
capi-kubeadm-control-plane-system   kubeadm-control-plane   controlPlane     kubeadm        v1.4.6             Ready
capi-system                         cluster-api             core             cluster-api    v1.4.6             Ready
rke2-bootstrap-system               rke2-bootstrap          bootstrap        rke2           v0.2.6             Ready
rke2-control-plane-system           rke2-control-plane      controlPlane     rke2           v0.2.6             Ready
```

In previous versions only infra providers used to listed:
```
$ kubectl get infrastructureproviders -A
NAMESPACE     NAME     INSTALLEDVERSION   READY
capd-system   docker   v1.4.6             True

```

**Screenshots**
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/3ca2ebe5-c9f1-48b1-ae3b-9cec64cbcaf2)

cc: @richardcase

**Comment by eva-vashkevich** [comment]
I've checked with Ken and we decided to rename CAPI Clusters to Clusters and Infrastructure providers to Providers for better consistency.
