### ISSUE TITLE
Unable to edit an infrastructure provider

### ISSUE THREAD

**Issue by valaparthvi** [rancher/capi-ui-extension#47]
1. Create and infrastructure provider.
2. Once created, select `Edit Config` from the kebab menu.
3. Try to change cloud credential or update features, add variable or change description.

Errors out with:
`Operation cannot be fulfilled on capiproviders.turtles-capi.cattle.io "azure": the object has been modified; please apply your changes to the latest version and try again`

**Comment by valaparthvi** [comment]
Still seeing this error when I try to edit the provider via YAML.

Steps to reproduce:
1. Create a Provider.
2. Once it is Active, Select `Edit YAML` from the Kebab menu.
3. Make a change, and hit save.

![image](https://github.com/rancher/capi-ui-extension/assets/11015077/d447758e-f77f-4b07-8a8f-00df26d04cd3)

4. Click on `Cancel`.

![image](https://github.com/rancher/capi-ui-extension/assets/11015077/9270658b-bb50-41d4-8906-bbb67b95a180)

**Comment by eva-vashkevich** [comment]
It looks like when saving YAMLs dashboard doesn't handle conflicts. It would be better to fix tis issue there instead of making it specific to capi provider. I've opened https://github.com/rancher/dashboard/issues/10972 to track it and disabled editing YAML until it is resolved.
