### ISSUE TITLE
Add placeholder text to URL field while creating custom provider

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#48]
**Setup**
Rancher version: v2.8-head
Rancher Turtles: v0.6.0
Rancher UI Extensions: CAPI UI Extension v0.4.0
Browser type & version: Chrome Latest

**To Reproduce**
- Install CAPI UI extension
- Open Cluster Management > CAPI Menu
- Open Infrastructure Providers > Create > Custom

**Expected Result**
url should be in the form: https://github.com/{owner}/{Repository}/releases/{latest|version-tag}/{componentsClient.yaml}
Placeholder text can be added for the same.

**Screenshots**
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/54b5f0a1-76da-4ab3-9def-7efe3e6250ef)

**Comment by eva-vashkevich** [comment]
Hi @cpinjani
https://github.com/{owner}/{Repository}/releases/{latest|version-tag}/{componentsClient.yaml} is long and pretty hard to read, would
https://github.com/example/releases/latest/client.yaml be okay?
Thank you

**Comment by cpinjani** [comment]
`https://github.com/example/releases/latest/componentsClient.yaml`
should be fine IMO

**Comment by cpinjani** [comment]
Validated as fixed on UI extension v0.5.0-rc1
