### ISSUE TITLE
[BUG] ConfigSecret name uses cached value which mismatches with provider 

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#52]
**Setup**
Rancher version: v2.8-head
Rancher Turtles: v0.6.0
Rancher UI Extensions: CAPI UI Extension v0.4.0
Browser type & version: Chrome Latest

**To Reproduce**
- Install CAPI UI extension
- Open Cluster Management > CAPI Menu
- Open Infrastructure Providers > Create > Docker > Create
- Now Create AWS Infra provider (Edit YAML and check ConfigSecret name)
Config secret is created with name _docker-credentials-*_, if user does not edits YAML

**Expected Result**
ConfigSecret name must match with provider or should be provider agnostic

**Screenshots**
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/61985796-b4ee-4e86-95f5-ed98af59823c)

**Comment by eva-vashkevich** [comment]
Hi, this was by design to avoid accidental name collision. Why do you think this is wrong?

**Comment by cpinjani** [comment]
Since it creates with name _**docker**-credentials-*_ for all other providers if below steps are performed:
- Open Infrastructure Providers > Create > Docker > Create
- Now Create AWS Infra provider or any other Infra provider

**Comment by eva-vashkevich** [comment]
Ah I see the issue. It has been fixed as part of https://github.com/rancher/capi-ui-extension/pull/50

**Comment by cpinjani** [comment]
Validated as fixed on UI extension v0.5.0-rc1
