### ISSUE TITLE
Error when enabling a custom provider without a version

### ISSUE THREAD

**Issue by richardcase** [rancher/capi-ui-extension#60]
When enabling a custom provider and not specifying a version the request silently fails.

To repro:
- In Rancher Manager go to Cluster Management->CAPI->Providers
- Click **Create**
- Click **Custom**
- Enter the following:
  - **Name:** kubeadm-bootstrap
  - **Provider:**: kubeadm
  - **Provider Type:** Bootstrap
- Click **Create**

Looking at the request/response you see it sends:

```json
{
    "type": "turtles-capi.cattle.io.capiprovider",
    "metadata": {
        "namespace": "default",
        "name": "kubeadm-controlplane"
    },
    "spec": {
        "name": "kubeadm",
        "type": "controlPlane",
        "configSecret": {
            "name": "custom-credentials-zwa8c"
        },
        "credentials": null,
        "fetchConfig": {
            "url": ""
        },
        "version": "",
        "features": {
            "clusterResourceSet": true,
            "clusterTopology": true,
            "machinePool": true
        },
        "variables": {}
    }
}
```

And this responds with an error:

```json
{
    "type": "error",
    "links": {},
    "code": "Invalid",
    "message": "CAPIProvider.turtles-capi.cattle.io \"kubeadm-controlplane\" is invalid: spec: Invalid value: \"object\": CAPI Provider version should be in the semver format prefixed with 'v'. Example: v1.9.3",
    "status": 422,
    "type": "error"
}
```

It feels like there are 2 issues here:

- [ ] Errors should be reported to the user
- [ ] If there is no value entered then the front end shouldn't send the field in the request.

**Comment by cpinjani** [comment]
Also, version field should allow custom such as [v1.3.3-cabpr-fix](https://github.com/belgaied2/cluster-api/releases/v1.3.3-cabpr-fix/)
![image](https://github.com/rancher/capi-ui-extension/assets/73099870/26c87a15-8ae2-4b8a-8de1-d45aa5fa26ed)

**Comment by eva-vashkevich** [comment]
Hi @alexander-demicev
Docs should be updated to indicate that version field is required. Do you know what ticket is needed for that?
