### ISSUE TITLE
Create cluster class from UI fails

### ISSUE THREAD

**Issue by richardcase** [rancher/capi-ui-extension#61]
When creating a cluster class from the UI using the ["quick start" example](https://github.com/rancher/highlander/blob/main/demos/may2024/data/clusterclass.yaml) it fails with the following error:

`expected a single document in the stream, but found more`

When creating a clusterclass we need to allow "multiple document" yaml files as a cluster class is made up of multiple documents.

To repro:
- In Rancher Manager go to Cluster Management->CAPI->Cluster Classes
- Click **Create**
- Paste in the contents of the quick start sample 
- Click Create

**Comment by cpinjani** [comment]
Related issue: https://github.com/rancher/capi-ui-extension/issues/15

**Comment by richardcase** [comment]
Sorry @cpinjani i missed that.
