### ISSUE TITLE
Release version compatible with rancher 2.9+

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/capi-ui-extension#82]
Turtles are bumping minimal required version to 2.9 in https://github.com/rancher/turtles/pull/672, which renders current release of UI unable to run on the version.

**Comment by eva-vashkevich** [comment]
Hi @Danil-Grigorev what do you mean by "enders current release of UI unable to run on the version" ? latest capi ui release is compatible with 2.9

**Comment by Danil-Grigorev** [comment]
I believe the reason I was not able to install the extension is due to using alpha version of rancher or kubernetes 1.30.3. This can be closed then.
